webApp/src/Entity/Task.php
<?php

namespace App\Entity;

use App\Repository\TaskRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TaskRepository::class)]
class Task
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?bool $completed = false;

    #[ORM\Column(nullable: true)]
    private ?int $difficulty = 1;

    #[ORM\Column(nullable: true)]
    private ?int $xp_reward = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $recurrence = 'Once';

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\ManyToOne(inversedBy: 'tasks')]
    private ?User $user = null;

    #[ORM\OneToOne(mappedBy: 'task', cascade: ['persist', 'remove'])]
    private ?TaskStats $taskStatid = null;

    #[ORM\Column(length: 25, nullable: true)]
    private ?string $type = null;

    #[ORM\Column(nullable: true)]
    private ?bool $failed = false;

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function isCompleted(): ?bool
    {
        return $this->completed;
    }

    public function setCompleted(bool $completed): static
    {
        $this->completed = $completed;

        return $this;
    }

    public function getDifficulty(): ?int
    {
        return $this->difficulty;
    }

    public function setDifficulty(?int $difficulty): static
    {
        $this->difficulty = $difficulty;

        return $this;
    }

    public function getXpReward(): ?int
    {
        return $this->xp_reward;
    }

    public function setXpReward(?int $xp_reward): static
    {
        $this->xp_reward = $xp_reward;

        return $this;
    }

    public function getRecurrence(): ?string
    {
        return $this->recurrence;
    }

    public function setRecurrence(?string $recurrence): static
    {
        $this->recurrence = $recurrence;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getTaskStatid(): ?TaskStats
    {
        return $this->taskStatid;
    }

    public function setTaskStatid(?TaskStats $taskStatid): static
    {
        // unset the owning side of the relation if necessary
        if ($taskStatid === null && $this->taskStatid !== null) {
            $this->taskStatid->setTask(null);
        }

        // set the owning side of the relation if necessary
        if ($taskStatid !== null && $taskStatid->getTask() !== $this) {
            $taskStatid->setTask($this);
        }

        $this->taskStatid = $taskStatid;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
    }

    public function isFailed(): ?bool
    {
        return $this->failed;
    }

    public function setFailed(?bool $failed): static
    {
        $this->failed = $failed;

        return $this;
    }





}

webApp/src/Form/TaskType.php
<?php

namespace App\Form;

use App\Entity\Task;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('difficulty', choiceType::class, [
                'choices' => [
                    'Easy' => '1',
                    'Medium' => '2',
                    'Hard' => '3',
                ],
                'multiple' => false
            ])
            ->add('type', ChoiceType::class, ['choices' => [
                'Strength' => 'Strength',
                'Intelligence' => 'Intelligence',
                'Constitution' => 'Constitution',
                'Charisma' => 'Charisma',
            ]])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Task::class,
        ]);
    }
}

webApp/src/Controller/TaskController.php
<?php

namespace App\Controller;

use App\Entity\Achievements;
use App\Entity\Task;
use App\Entity\User;
use App\Form\TaskType;
use App\Repository\TaskRepository;
use App\Repository\UserRepository;
use App\Service\TaskManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/task')]
class TaskController extends AbstractController
{
    #[Route('/', name: 'app_task_index', methods: ['GET'])]
    public function index(TaskRepository $taskRepository): Response
    {
        return $this->render('task/index.html.twig', [
            'tasks' => $taskRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_task_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $task = new Task();
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($task->getDifficulty() === 1) {
                $task->setXpReward(15);
            } elseif ($task->getDifficulty() === 2) {
                $task->setXpReward(25);
            } else {
                $task->setXpReward(40);
            }

            $task->setUser($this->getUser());
            $entityManager->persist($task);
            $entityManager->flush();

            return $this->redirectToRoute('app_user_show', ['id' => $task->getUser()->getId()]);
        }

        return $this->render('task/new.html.twig', [
            'task' => $task,
            'form' => $form,
        ]);
    }
    #[Route('/redo/{id}', name: 'app_task_redo', methods: ['GET'])]
    public function redo($id , EntityManagerInterface $entityManager): Response
    {
        $task = $entityManager->getRepository(Task::class)->find($id);
        $task->setCompleted(false);
        $entityManager->flush();
        return $this->redirectToRoute('app_user_show', ['id' => $task->getUser()->getId()]);
    }

    #[Route('/{id}', name: 'app_task_show', methods: ['GET'])]
    public function show(Task $task): Response
    {
        return $this->render('task/show.html.twig', [
            'task' => $task,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_task_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Task $task, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $task->setUser($this->getUser());
            $entityManager->flush();

            return $this->redirectToRoute('app_user_show', ['id' => $task->getUser()->getId()]);
        }

        return $this->render('task/edit.html.twig', [
            'task' => $task,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_task_delete', methods: ['POST'])]
    public function delete(Request $request, Task $task, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $task->getId(), $request->request->get('_token'))) {
            $entityManager->remove($task);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_task_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/user/task/{id}', name: 'get_user_tasks', methods: ['GET'])]
    public function getUserTasks(TaskRepository $taskRepository, $id): Response
    {
        $tasks = $taskRepository->findByUserId($id);
        return $this->render('task/user_tasks.html.twig', ['userTasks' => $tasks]);
    }

    #[Route('/taskdone/{id}', name: 'task_done', methods: ['PATCH', 'POST'])]
    public function taskDone($id, TaskRepository $taskRepository, EntityManagerInterface $entityManager, TaskManager $taskManager, UserRepository $userRepository): Response
    {
        $userId = $this->getUser()->getId();
        $user = $userRepository->find($userId);
        $task = $taskRepository->find($id);
        $taskManager->questDone($user, $task);


        $entityManager->flush();

        return $this->redirectToRoute('app_user_show', ['id' => $task->getUser()->getId()]);
    }

}

webApp/templates/task/_delete_form.html.twig
<form method="post" action="{{ path('app_task_delete', {'id': task.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ task.id) }}">
    <button class="btn">Delete</button>
</form>

webApp/templates/task/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Task{% endblock %}

{% block body %}


<!-- Modal Form Container -->
<div id="editTaskModal" class="h-[calc(100vh-44px)] flex items-center justify-center bg-[url('/images/background.webp')] opacity-90 bg-cover bg-center ">
    <div class="relative p-4 w-full max-w-2xl">
        <!-- Modal content -->
        <div class="bg-[#967969] border-4 border-black relative p-4 rounded-t-full shadow bg-sm:p-6">
            <!-- Modal header -->
            <div class="relative flex justify-center items-center mt-4 pb-4 mb-4 rounded-t sm:mb-5">
                <img src="{{ asset('/images/form/newQuestForm.png') }}" class="h-32">
                <button type="button"
                        onclick="window.location.href='{{ path('app_user_show' , {'id': app.user.id }) }}'"
                        class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 inline-flex items-center absolute top-0 right-0 ml-1 -mt-5"
                        data-modal-toggle="editTaskModal">
                    <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                              d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                              clip-rule="evenodd"></path>
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
            <!-- Modal body -->
            {{ form_start(form) }}
            <!-- Title -->
            <div class="pl-6 pr-6 pb-4">
                {{ form_row(form.title, {
                    'label': '<img src="/images/form/formTitle.png" alt="Title" class="inline h-12">',
                    'label_html': true,
                    'attr': {'class': 'bg-gray-50 border-4 border-black text-gray-900 text-sm rounded-lg focus:ring-yellow-600 focus:border-yellow-600 block w-full p-2.5 mt-4', 'placeholder': 'Task title'}
                }) }}
            </div>
            <!-- Selects -->
            <div class="pl-6 pr-6 pb-4 grid gap-8 mt-4 sm:grid-cols-2">
                <div>
                    {{ form_row(form.type, {
                        'label': '<img src="/images/form/formType.png" alt="Type" class="inline h-12">',
                        'label_html': true,
                        'label_attr': {'class': 'text-white'},
                        'attr': {'class': 'border-4 border-black mt-4 bg-white text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5'}
                    }) }}
                </div>
                <div>
                    {{ form_row(form.difficulty, {
                        'label': '<img src="/images/form/formDiff.png" alt="Difficulty" class="inline h-12">',
                        'label_html': true,
                        'label_attr': {'class': 'text-white'},
                        'attr': {'class': 'mt-4 bg-gray-50 border-4 border-black text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5'}
                    }) }}
                </div>
            </div>
            <!-- Description -->
            <div class="ml-2 mt-4 pl-4 pr-6 pb-4">
                {{ form_row(form.description, {
                    'label': '<img src="/images/form/formDescr.png" alt="Description" class="inline h-16 ml-4">',
                    'label_html': true,
                    'label_attr': {'class': 'text-white'},
                    'attr': {'class': 'mt-4 block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border-4 border-black focus:ring-primary-500 focus:border-primary-500 h-32', 'rows': '10', 'placeholder': 'Enter task details'}
                }) }}
            </div>
            <!-- Submit Button -->
            <div class="flex justify-center mt-6 ">
                <button type="submit"
                        class="text-white inline-flex items-center bg-orangePeel hover:bg-sky-500 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
                    <img width="20" height="20" src="https://img.icons8.com/ios-filled/50/FFFFFF/sword.png" class="mr-1.5" alt="sword"/>
                    Update Task!
                </button>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
</div>
{% endblock %}

webApp/templates/task/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Task index{% endblock %}

{% block body %}
    <h1>Task index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Description</th>
                <th>Completed</th>
                <th>Difficulty</th>
                <th>Xp_reward</th>
                <th>Recurrence</th>
                <th>Created_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for task in tasks %}
            <tr>
                <td>{{ task.id }}</td>
                <td>{{ task.title }}</td>
                <td>{{ task.description }}</td>
                <td>{{ task.completed ? 'Yes' : 'No' }}</td>
                <td>{{ task.difficulty }}</td>
                <td>{{ task.xpReward }}</td>
                <td>{{ task.recurrence }}</td>
                <td>{{ task.createdAt ? task.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_task_show', {'id': task.id}) }}">show</a>
                    <a href="{{ path('app_task_edit', {'id': task.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_task_new') }}">Create new</a>
{% endblock %}

webApp/templates/task/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Quest{% endblock %}

{% block body %}
    <!-- Main modal -->
    <div id="defaultModal" class="h-[calc(100vh-44px)] flex items-center justify-center bg-[url('/images/bgtest.jpg')] -mt-1 bg-cover bg-center  ">
        <div class="relative p-2 w-full max-w-2xl">
            <!-- Modal content -->
            <div class="bg-[url('/images/backgroundtrophy2.png')] bg-cover bg-center border- border-2 border-black relative p-4 rounded-t-full  shadow bg-sm:p-6">
                <!-- Modal header -->
                <div class="relative flex justify-center items-center mt-4 pb-4 mb-4 rounded-t sm:mb-5">
                    <img src="{{ asset('/images/form/newQuestForm.png') }}" class="h-32">
                    <button type="button"
                            onclick="window.location.href='{{ path('app_user_show' , {'id': app.user.id }) }}'"
                            class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 inline-flex items-center absolute top-0 right-0 ml-1 -mt-5"
                            data-modal-toggle="defaultModal">
                        <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"
                             xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                  d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                                  clip-rule="evenodd"></path>
                        </svg>
                        <span class="sr-only">Close modal</span>
                    </button>
                </div>
                <!-- Modal body -->
                {{ form_start(form) }}
                <!-- Title -->
                <div class="pl-6 pr-6 pb-4">
                    {{ form_row(form.title, {
                        'label': '<img src="/images/form/formTitle.png" alt="Title" class="inline h-12">',
                        'label_html': true,
                        'attr': {'class': 'bg-gray-50 text-black border-2 border-teaGreen  opacity-80 text-sm rounded-lg focus:ring-yellow-600 focus:border-yellow-600 block w-full p-2.5 mt-4', 'placeholder': 'Quest title'}
                    }) }}
                </div>
                <!-- Selects -->
                <div class="pl-6 pr-6 pb-4 grid gap-8 mt-4 sm:grid-cols-2">
                    <div>
                        {{ form_row(form.type, {
                            'label': '<img src="/images/form/formType.png" alt="Title" class="inline h-12">',
                            'label_html': true,
                            'label_attr': {'class': 'text-white'},
                            'attr': {'class': 'border-2 border-teaGreen  mt-4 bg-white text-black text-sm opacity-80 rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5'}
                        }) }}
                    </div>
                    <div>
                        {{ form_row(form.difficulty, {
                            'label': '<img src="/images/form/formDiff.png" alt="Title" class="inline h-12">',
                            'label_html': true,
                            'label_attr': {'class': 'text-white'},
                            'attr': {'class': 'mt-4 bg-gray-50 border-2 border-teaGreen  text-gray-900 text-sm opacity-80 rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5'}
                        }) }}
                    </div>
                </div>
                <!-- Description -->
                <div class="ml-2 mt-4 pl-4 pr-6 pb-4">
                    {{ form_row(form.description, {
                        'label': 'Description',
                        'label': '<img src="/images/form/formDescr.png" alt="Title" class="inline h-16 ml-4">',
                        'label_html': true,
                        'label_attr': {'class': 'text-white'},
                        'attr': {'class': 'mt-4 block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border-2 opacity-80 border-teaGreen  focus:ring-primary-500 focus:border-primary-500 h-32' , 'rows': '10', 'placeholder': 'SAL ALGO PORFAVÓ ODIO EL ESTILADO'},

                    }) }}
                </div>
                <!-- Submit Button -->
                <div class="flex justify-center mt-6 ">
                    <button type="submit"
                            class="text-black bangers-regular text-3xl inline-flex items-center bg-orangePeel hover:bg-tyrianPurple border-2 border-black focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg  px-5 py-2.5 text-center">
                        <img width="20" height="20" src="https://img.icons8.com/ios-filled/50/FFFFFF/sword.png" class="mr-1.5" alt="sword"/>
                        Embark on a quest!
                    </button>
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

webApp/templates/task/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Task{% endblock %}

{% block body %}
    <h1>Task</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ task.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ task.title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ task.description }}</td>
            </tr>
            <tr>
                <th>Completed</th>
                <td>{{ task.completed ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Difficulty</th>
                <td>{{ task.difficulty }}</td>
            </tr>
            <tr>
                <th>Xp_reward</th>
                <td>{{ task.xpReward }}</td>
            </tr>
            <tr>
                <th>Recurrence</th>
                <td>{{ task.recurrence }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ task.createdAt ? task.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_task_index') }}">back to list</a>

    <a href="{{ path('app_task_edit', {'id': task.id}) }}">edit</a>

    {{ include('task/_delete_form.html.twig') }}
{% endblock %}

webApp/templates/task/user_tasks.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {% for task in userTasks %}
        <div>{{ task.title }}</div>
        <p>{{ task.description }}</p>
    {% endfor %}

{% endblock %}