webApp/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 100)]
    private ?string $username = null;

    #[ORM\Column(nullable: true)]
    private ?int $current_level = null;

    #[ORM\Column(nullable: true)]
    private ?int $current_xp = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $profession = null;

    #[ORM\Column(nullable: true)]
    private ?int $strength = null;

    #[ORM\Column(nullable: true)]
    private ?int $intelligence = null;

    #[ORM\Column(nullable: true)]
    private ?int $constitution = null;

    #[ORM\Column(nullable: true)]
    private ?int $charisma = null;

    #[ORM\Column(nullable: true)]
    private ?int $xp_required = null;

    #[ORM\OneToMany(targetEntity: Task::class, mappedBy: 'user')]
    private Collection $tasks;

    #[ORM\Column(nullable: true)]
    private ?int $str_xp_rq = 100;

    #[ORM\Column(nullable: true)]
    private ?int $int_xp_rq = 100;

    #[ORM\Column(nullable: true)]
    private ?int $const_xp_rq = 100;

    #[ORM\Column(nullable: true)]
    private ?int $cha_xp_rq = 100;

    #[ORM\Column(nullable: true)]
    private ?int $str_current = 0;

    #[ORM\Column(nullable: true)]
    private ?int $int_current = 0;

    #[ORM\Column(nullable: true)]
    private ?int $const_current = 0;

    #[ORM\Column(nullable: true)]
    private ?int $cha_current = 0;

    #[ORM\OneToMany(targetEntity: Achievements::class, mappedBy: 'user')]
    private Collection $achievements;

    public function __construct()
    {
        $this->tasks = new ArrayCollection();
        $this->achievements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getCurrentLevel(): ?int
    {
        return $this->current_level;
    }

    public function setCurrentLevel(?int $current_level): static
    {
        $this->current_level = $current_level;

        return $this;
    }

    public function getCurrentXp(): ?int
    {
        return $this->current_xp;
    }

    public function setCurrentXp(?int $current_xp): static
    {
        $this->current_xp = $current_xp;

        return $this;
    }

    public function getProfession(): ?string
    {
        return $this->profession;
    }

    public function setProfession(?string $profession): static
    {
        $this->profession = $profession;

        return $this;
    }

    public function getStrength(): ?int
    {
        return $this->strength;
    }

    public function setStrength(?int $strength): static
    {
        $this->strength = $strength;

        return $this;
    }

    public function getIntelligence(): ?int
    {
        return $this->intelligence;
    }

    public function setIntelligence(?int $intelligence): static
    {
        $this->intelligence = $intelligence;

        return $this;
    }

    public function getConstitution(): ?int
    {
        return $this->constitution;
    }

    public function setConstitution(?int $constitution): static
    {
        $this->constitution = $constitution;

        return $this;
    }

    public function getCharisma(): ?int
    {
        return $this->charisma;
    }

    public function setCharisma(?int $charisma): static
    {
        $this->charisma = $charisma;

        return $this;
    }

    public function getXpRequired(): ?int
    {
        return $this->xp_required;
    }

    public function setXpRequired(?int $xp_required): static
    {
        $this->xp_required = $xp_required;

        return $this;
    }

    /**
     * @return Collection<int, Task>
     */
    public function getTasks(): Collection
    {
        return $this->tasks;
    }

    public function addTask(Task $task): static
    {
        if (!$this->tasks->contains($task)) {
            $this->tasks->add($task);
            $task->setUser($this);
        }

        return $this;
    }

    public function removeTask(Task $task): static
    {
        if ($this->tasks->removeElement($task)) {
            // set the owning side to null (unless already changed)
            if ($task->getUser() === $this) {
                $task->setUser(null);
            }
        }

        return $this;
    }

    public function getStrXpRq(): ?int
    {
        return $this->str_xp_rq;
    }

    public function setStrXpRq(?int $str_xp_rq): static
    {
        $this->str_xp_rq = $str_xp_rq;

        return $this;
    }

    public function getIntXpRq(): ?int
    {
        return $this->int_xp_rq;
    }

    public function setIntXpRq(?int $int_xp_rq): static
    {
        $this->int_xp_rq = $int_xp_rq;

        return $this;
    }

    public function getConstXpRq(): ?int
    {
        return $this->const_xp_rq;
    }

    public function setConstXpRq(?int $const_xp_rq): static
    {
        $this->const_xp_rq = $const_xp_rq;

        return $this;
    }

    public function getChaXpRq(): ?int
    {
        return $this->cha_xp_rq;
    }

    public function setChaXpRq(?int $cha_xp_rq): static
    {
        $this->cha_xp_rq = $cha_xp_rq;

        return $this;
    }

    public function getStrCurrent(): ?int
    {
        return $this->str_current;
    }

    public function setStrCurrent(?int $str_current): static
    {
        $this->str_current = $str_current;

        return $this;
    }

    public function getIntCurrent(): ?int
    {
        return $this->int_current;
    }

    public function setIntCurrent(int $int_current): static
    {
        $this->int_current = $int_current;

        return $this;
    }

    public function getConstCurrent(): ?int
    {
        return $this->const_current;
    }

    public function setConstCurrent(?int $const_current): static
    {
        $this->const_current = $const_current;

        return $this;
    }

    public function getChaCurrent(): ?int
    {
        return $this->cha_current;
    }

    public function setChaCurrent(?int $cha_current): static
    {
        $this->cha_current = $cha_current;

        return $this;
    }

    /**
     * @return Collection<int, Achievements>
     */
    public function getAchievements(): Collection
    {
        return $this->achievements;
    }

    public function addAchievement(Achievements $achievement): static
    {
        if (!$this->achievements->contains($achievement)) {
            $this->achievements->add($achievement);
            $achievement->setUser($this);
        }

        return $this;
    }

    public function removeAchievement(Achievements $achievement): static
    {
        if ($this->achievements->removeElement($achievement)) {
            // set the owning side to null (unless already changed)
            if ($achievement->getUser() === $this) {
                $achievement->setUser(null);
            }
        }

        return $this;
    }
}

webApp/src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email')
            ->add('roles', choiceType::class, ['choices'=>['user'=>'ROLE_USER','admin'=>'ROLE_ADMIN'] , 'expanded'=>true, 'multiple'=>true])
            ->add('password')
            ->add('username')
            ->add('current_level')
            ->add('current_xp')
            ->add('profession')
            ->add('strength')
            ->add('intelligence')
            ->add('constitution')
            ->add('charisma')
            ->add('xp_required')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

webApp/src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;

#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/', name: 'app_user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/profession', name: 'app_user_profession', methods: ['GET'])]
    public function profession(UserRepository $userRepository): Response
    {
        return $this->render('user/profession.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }


    #[Route('/{id}', name: 'app_user_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        $userTasks = $user->getTasks()->toArray();
        return $this->render('user/show.html.twig', [
            'user' => $user,
            'userTasks' => $userTasks
        ]);
    }

    #[Route('/{id}/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }


    #[Route('/profession', name: 'app_user_profession_choices', methods: ['POST', 'GET'])]
    public function addProfession(Request $request, EntityManagerInterface $entityManager): Response
    {
        $profession = $request->get('profession');
        $user = $this->getUser();
        $user->setProfession($profession);
        $entityManager->persist($user);
        $entityManager->flush();
        return $this->redirectToRoute('app_user_show', ['id' => $user->getId()]);
    }

    #[Route('/{id}', name: 'app_user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $user->getId(), $request->request->get('_token'))) {
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
    }

}

webApp/templates/user/2show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ user.id }}</td>
        </tr>
        <tr>
            <th>Email</th>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <th>Username</th>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <th>Current_level</th>
            <td>{{ user.currentLevel }}</td>
        </tr>
        <tr>
            <th>Current_xp</th>
            <td>{{ user.currentXp }}</td>
        </tr>
        <tr>
            <th>Profession</th>
            <td>{{ user.profession }}</td>
        </tr>
        <tr>
            <th>Strength</th>
            <td>{{ user.strength }}</td>
        </tr>
        <tr>
            <th>Strength Current</th>
            <td>{{ user.strCurrent }}</td>
        </tr>
        <tr>
            <th>Intelligence</th>
            <td>{{ user.intelligence }}</td>
        </tr>
        <tr>
            <th>Charisma Current</th>
            <td>{{ user.intCurrent }}</td>
        </tr>
        <tr>
            <th>Constitution</th>
            <td>{{ user.constitution }}</td>
        </tr>
        <tr>
            <th>Charisma Current</th>
            <td>{{ user.constCurrent }}</td>
        </tr>
        <tr>
            <th>Charisma</th>
            <td>{{ user.charisma }}</td>
        </tr>
        <tr>
            <th>Charisma Current</th>
            <td>{{ user.chaCurrent }}</td>
        </tr>
        <tr>
            <th>Xp_required</th>
            <td>{{ user.xpRequired }}</td>
        </tr>
        <tr>
            <th>Strength XP</th>
            <td>{{ user.StrXpRq }}</td>
        </tr>

        </tbody>
    </table>

    {% if app.user.profession == 'Warrior' %}
        <img id="loginImage"
             src="https://e7.pngegg.com/pngimages/326/398/png-clipart-viking-ships-cartoon-viking-warrior-s-cartoonist-fictional-character.png"
             alt="login-image" class="mx-auto mb-8 w-96"/>
        {{ include('user/_delete_form.html.twig') }}
    {% endif %}
    {% if app.user.profession == 'Mage' %}
        <img id="loginImage"
             src="https://png.pngtree.com/png-vector/20240601/ourmid/pngtree-necromancer-character-with-a-mischievous-png-image_12599219.png"
             alt="login-image" class="mx-auto mb-8 w-96"/>
    {% endif %}

    {% if app.user.profession == 'Rogue' %}
        <img id="loginImage"
             src="https://img.freepik.com/fotos-premium/assassin-rogue-traje-furtivo-negro-gris-hombre-teena-lindo-personaje-guerrero-ilustracion_1020495-735699.jpg"
             alt="login-image" class="mx-auto mb-8 w-96"/>
    {% endif %}

    {% block tasks %}
        <div class="container mx-auto max-w-lg mt-10 p-4 bg-gray-100 rounded-lg shadow-md">
            <h1 class="text-center font-bold text-4xl text-blue-950 mb-8">Quests</h1>

            <div class="mb-8">
                {% for task in userTasks %}
                    {% if not task.completed %}
                        <div class="mb-6 p-4 bg-white rounded-lg shadow">
                            <p class="text-center text-gray-700 mt-2">{{ task.type }}</p>
                            <a href="{{ path('app_task_edit', {'id': task.id}) }}"
                               class="block text-center font-bold text-blue-950 text-xl">
                                {{ task.title }}
                            </a>

                            <p class="text-center text-gray-700 mt-2">{{ task.description }}</p>
                            <div class="flex justify-center space-x-4 mt-4">
                                <form action="{{ path('task_done', {'id': task.id}) }}" method="POST">
                                    <input type="hidden" name="_method" value="PATCH">
                                    <button type="submit"
                                            class="bg-green-500 hover:bg-green-600 text-black font-bold py-2 px-4 rounded w-32">
                                        Complete!
                                    </button>
                                </form>
                                <form action="{{ path('app_task_delete', {'id': task.id}) }}" method="POST">
                                    <button type="submit"
                                            class="bg-green-500 hover:bg-green-600 text-black font-bold py-2 px-4 rounded w-32">
                                        Forfeit
                                    </button>
                                </form>
                                <form action="{{ path('app_task_edit', {'id': task.id}) }}" method="POST">
                                    <input type="hidden" name="_method" value="PATCH">
                                    <button type="submit"
                                            class="bg-green-500 hover:bg-green-600 text-black font-bold py-2 px-4 rounded w-32">
                                        Edit
                                    </button>
                                </form>
                            </div>

                            {% endif %}
                {% endfor %}
            </div>

            <div class="text-center mb-8">
                <button class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-6 rounded"
                        onclick="window.location.href='{{ path('app_task_new') }}'">
                    Add a New Quest!
                </button>
            </div>

            <h2 class="text-center font-bold text-3xl text-blue-950 mb-6">Finished:</h2>
            <div>
                {% for task in userTasks|reverse|slice(0,5) %}
                    {% if task.completed %}
                        <div class="mb-6 p-4 bg-white rounded-lg shadow">
                            <a href="{{ path('app_task_edit', {'id': task.id}) }}"
                               class="block text-center font-bold text-blue-800 text-xl">
                                {{ task.title }}
                            </a>
                            <p class="text-center text-gray-600 mt-2">{{ task.description }}</p>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    {% endblock %}

    <a href="{{ path('app_user_index') }}">back to list</a>

    <a href="{{ path('app_user_edit', {'id': user.id}) }}">edit</a>

{% endblock %}

webApp/templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

webApp/templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_user_show') , {'id': app.user.id }}}">back to list</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

webApp/templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>User index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Password</th>
                <th>Username</th>
                <th>Current_level</th>
                <th>Current_xp</th>
                <th>Profession</th>
                <th>Strength</th>
                <th>Intelligence</th>
                <th>Constitution</th>
                <th>Charisma</th>
                <th>Xp_required</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.currentLevel }}</td>
                <td>{{ user.currentXp }}</td>
                <td>{{ user.profession }}</td>
                <td>{{ user.strength }}</td>
                <td>{{ user.intelligence }}</td>
                <td>{{ user.constitution }}</td>
                <td>{{ user.charisma }}</td>
                <td>{{ user.xpRequired }}</td>
                <td>
                    <a href="{{ path('app_user_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('app_user_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="14">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_user_new') }}">Create new</a>
{% endblock %}

webApp/templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('app_user_index') }}">back to list</a>
{% endblock %}